"""empty message

Revision ID: 6ea3a92293c7
Revises: 63a2270e87f1
Create Date: 2018-01-22 16:27:02.305113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ea3a92293c7'
down_revision = '63a2270e87f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('board', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('board', 'create_time')
    # ### end Alembic commands ###
